# Generated by Django 2.1.7 on 2019-02-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='daily_photo',
        ),
    ]
