# Generated by Django 2.1.7 on 2019-02-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
